fix(sharelink): Changed the layout and functionality for sharing a link, according to Stefan's wishes
Lamineslot/projectagile-SOi pull request #45
Opened 2023-04-25 12:53 UTC by Lamineslot

Middels deze pull request wordt PW-5 afgerond. Op basis van de feedback van Stefan is de standaardlink verwijderd. Er is nu enkel een mogelijkheid om een custom link aan te maken. De gebruiker kan nu enkel de alias/slug invullen. De basis-URL staat al ingevuld.

Je kunt deze PR testen door het testscenario van PW-5 uit te voeren.

2023-04-25 19:34 UTC, Anas073 requested changes

2023-04-25 19:34 UTC, Anas073 commented on resources/views/competition/show.blade.php
> +                                        </div>
De format van de link klopt niet helemaal

![afbeelding](https://user-images.githubusercontent.com/82931055/234383548-db49b479-4d4f-4eed-9eea-bf172a733ec9.png)

2023-04-26 08:19 UTC, Lamineslot commented on resources/views/competition/show.blade.php
> +                                        </div>
Klopt, is nu opgelost

2023-04-26 08:51 UTC, Anas073 approved these changes
Na de verandering werkt alles prima.

2023-04-26 09:51 UTC, JeromeNL approved these changes
Netjes opgelost! Na het aanpassen van 'APP_URL' naar '=http://127.0.0.1:8000' werkte alles correct. Moeten we dus even op letten bij deployment.

2023-04-26 10:13 UTC, merged